import Head from 'next/head';
import{BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube,AiFillInstagram} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState} from 'react';




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ardian Osmani Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section >
        <nav className='py-10 mb-12 flex justify-between dark:text-white'>
          <h1 className='text-xl font-normal'>DevelopedByAO</h1>
          <ul className='flex items-center'>
            <li><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/></li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
          </ul>
        </nav>
        <div className='text-center p-10  py-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Ardian Osmani</h2>
          <h3 className='text-2xl py-2 text-teal-300 md:text-3xl'>Developer & Designer</h3>
          <p className='text-medium py-5 leading-8 text-gray-800 max-w-lg mx-auto'>Junior Programmer providing services for programming and design content needs.
            Join me down below an let's get Working!
          </p>
        </div>
        <div className='text-4xl flex justify-center gap-16 py-3 text-gray-600 md:text-xl'>
          <AiFillTwitterCircle/>
          <AiFillLinkedin/>
          <AiFillYoutube/>
          <AiFillInstagram/>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
          <Image src={deved} layout='fill' objectFit='cover'/>
        </div>
      </section>
      <section>
        <div>
          <h3 className='text-3xl py-1 text-blue-500'>Services I Offer</h3>
          <p className='text-md py-2 leading-8 text-gray-800'>
            Since the Beginning of my journey as a <span className='text-teal-300'> Junior Front-End Developer</span> i've been able to <span className='text-teal-500'>Create</span> Websites perfectly designed for the Clients
          </p>
          <p>
            I Offer a Wide Range of services,including <span className='text-teal-500'>Brand Design</span>,<span className='text-teal-500'>Web Design</span> and <span className='text-teal-500'>Digital Marketing</span>.
          </p>
        </div>
        <div className='gap-10 lg:flex-5'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
            <Image src={design} width={100} height={100}/>
            <h3 className='text-large font-medium pt-9 pb-2'>Brand Design</h3>
            <p className='py-2'>Creating elegant <span className='text-teal-600'>Design</span> suited for you'r needs following core design theory</p>
            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
            <p className='text-gray-800 py-1'>Photoshop</p>
            <p className='text-gray-800 py-1'>Figma</p>
            <p className='text-gray-800 py-1'>Illustrator</p>
          </div>
          </div>
          <div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 '>
            <Image src={code} width={100} height={100}/>
            <h3 className='text-large font-medium pt-9 pb-2'>Web Design</h3>
            <p className='py-2'>Creating understandable <span className='text-teal-600'>Code</span> suited for you'r needs following core design theory</p>
            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
            <p className='text-gray-800 py-1'>Reactjs</p>
            <p className='text-gray-800 py-1'>Vite</p>
            <p className='text-gray-800 py-1'>Tailwindcss</p>
          </div>
          </div>
          <div>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
            <Image src={consulting} width={100} height={100}/>
            <h3 className='text-large font-medium pt-9 pb-2'>Digital Marketing</h3>
            <p className='py-2'><span className='text-teal-600'>Consulting</span> for making the brand more attractive and safe for the clients </p>
            <h4 className='py-4 text-teal-600'>Design Tools I Use</h4>
            <p className='text-gray-800 py-1'>Google Ads</p>
            <p className='text-gray-800 py-1'>ChatGPT-3</p>
            <p className='text-gray-800 py-1'>MidJourney</p>
          </div>
          </div>
      </section>
      <section>
        <div>
          <h3 className='text-3xl py-1 text-blue-500'>Portofolio</h3>
          <p className='text-md py-2 leading-8 text-gray-800'>
            Since the Beginning of my journey as a <span className='text-teal-300'> Junior Front-End Developer</span> i've been able to <span className='text-teal-500'>Create</span> Websites perfectly designed for the Clients
          </p>
          <p>
            I Offer a Wide Range of services,including <span className='text-teal-500'>Brand Design</span>,<span className='text-teal-500'>Web Design</span> and <span className='text-teal-500'>Digital Marketing</span>.
          </p>
        </div>
        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
          <div className='basis-1  flex-1'><Image src={web1} className='rounded-lg object-cover'
           width={'50%'} height={'50%'} layout='responsive' /></div>
        </div>
        <div>
          <div className='basis-1  flex-2' ><Image src={web2} className='rounded-lg object-cover'
           width={'50%'} height={'50%'} layout="responsive"/></div>
        </div>
        <div>
          <div className='basis-1  flex-2'><Image src={web3} className='rounded-lg object-cover'
           width={'50%'} height={'50%'} layout='responsive'/></div>
        </div>
        <div>
          <div className='basis-1  flex-2' ><Image src={web4} className='rounded-lg object-cover'
           width={'50%'} height={'50%'} layout='responsive'/></div>
        </div>
        <div>
          <div className='basis-1  flex-2'><Image src={web5} className='rounded-lg object-cover'
           width={'50%'} height={'50%'} layout='responsive'/></div>
        </div>
        <div>
          <div className='basis-1  flex-2' ><Image src={web6} className='rounded-lg object-cover'
           width={'50%'} height={'50%'} layout='responsive'/></div>
        </div>
      </section>
      </main>
    </div>
  );
};
